backend:
  name: test-repo
  branch: main # Branch to update (optional; defaults to master)
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'
media_folder: public/img
public_folder: img
collections:
  - name: "schedules"
    label: "Schedules"
    folder: "content/schedules"
    create: true
    delete: true
    fields: 
      - {label: "Class Title", name: "class_title", widget: "string"}
      - {label: "Class Description", name: "class_description", widget: "string"}
      - {label: "Schedules", name: "schedules", widget: "markdown"}
      - {label: "Class fee", name: "class_fee", widget: "string"}
      - {label: "Material fee", name: "material_fee", widget: "string"}
      - {label: "Instructor", name: "instructor", widget: "string"}
      - {label: "Additional Info", name: "additional_info", widget: "markdown"}
  - name: "blogs"
    label: "Blog Posts"
    folder: "content/blogs"
    create: true
    delete: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", date_format: "MM.DD.YYYY", time_format: false }
      - {label: "Content", name: "content", widget: "markdown"}
  - name: "teachers"
    label: "Teachers"
    folder: "content/teachers"
    create: true
    delete: true
    fields:
      - {label: "Teacher Name", name: "teacher_name", widget: "string"}
      # - {label: "Instrument", name: "instrument", widget: "string"}
      # - {label: "Years of Experience", name: "years_of_experience", widget: "string"}
      # - {label: "Profile Picture", name: "profile_picture", widget: "image"}
      # - {label: "About", name: "about", widget: "markdown"}
 